# templates/fastapi-api/src/domain/ports/repositories.py
from typing import Protocol, Optional
from src.domain.entities.user import User
from src.domain.value_objects.email import Email
from uuid import UUID

class UserRepositoryPort(Protocol):
    async def save(self, user: User) -> User: ...
    async def find_by_id(self, user_id: UUID) -> Optional[User]: ...
    async def find_by_email(self, email: Email) -> Optional[User]: ...
    async def exists_by_email(self, email: Email) -> bool: ...
