// templates/next-frontend/src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/presentation/providers/query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = { title: "Clean Arch Next", description: "Generated by create next app" };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
